spring:
  config:
    import: 'consul:'
  application:
    name: order-processing
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        instance-id: order-processing
  sql:
    init:
      mode: never